export const courseCatalogURL: string = 'https://web.uri.edu/catalog/course-descriptions/';
export const studentOrgsCatalogURL: string = 'https://studentorg.apps.uri.edu/';

export const SECOND = 1000;
export const MINUTE = 60 * SECOND;
export const HOUR = 60 * MINUTE;
export const DAY = 24 * HOUR;

export const cacheTimeLimit = 10 * DAY;

export const courseCodes: Map<string, string>  = new Map(
    [
        ['AAF', 'AAF - Africana Studies'],
        ['ACC', 'ACC - Accounting'],
        ['AFS', 'AFS - Aquaculture and Fisheries Science'],
        ['AME', 'AME - American Studies'],
        ['AMS', 'AMS - Applied Mathematical Sciences'],
        ['APG', 'APG - Anthropology'],
        ['ARB', 'ARB - Arabic'],
        ['ART', 'ART - Art'],
        ['ASL', 'ASL - American Sign Language'],
        ['AST', 'AST - Astronomy'],
        ['AVS', 'AVS - Animal and Veterinary Science'],
        ['BAI', 'BAI - Business Analytics and Intelligence'],
        ['BES', 'BES - Biological and Environmental Studies'],
        ['BIO', 'BIO - Biological Sciences'],
        ['BIS', 'BIS - Bachelor of Interdisciplinary Studies'],
        ['BME', 'BME - Biomedical Engineering'],
        ['BPS', 'BPS - Biomedical and Pharmaceutical Sciences'],
        ['BTC', 'BTC - Biotechnology'],
        ['BUS', 'BUS - Business'],
        ['CCJ', 'CCJ - Criminology and Criminal Justice'],
        ['CHE', 'CHE - Chemical Engineering'],
        ['CHM', 'CHM - Chemistry'],
        ['CHN', 'CHN - Chinese'],
        ['CHS', 'CHS - College of Health Sciences'],
        ['CLA', 'CLA - Classics'],
        ['CLS', 'CLS - Comparative Literature Studies'],
        ['CMB', 'CMB - Cell and Molecular Biology'],
        ['CMD', 'CMD - Communicative Disorders'],
        ['COM','COM - Communication Studies'],
        ['CPL', 'CPL - Community Planning'],
        ['CRG', 'CRG - Continuous Registration'],
        ['CSC', 'CSC - Computer Science'],
        ['CSF', 'CSF - Digital Forensics and Cyber Security'],
        ['CSV', 'CSV - Community Service'],
        ['CVE', 'CVE - Civil and Environmental Engineering'],
        ['DBA', 'DBA - Doctorate of Business Admin'],
        ['DSP', 'DSP - Data Science Program'],
        ['ECN', 'ECN - Economics'],
        ['EDC', 'EDC - Education'],
        ['EDP', 'EDP - Ph.D. in Education'],
        ['EDS', 'EDS - Special Education'],
        ['EEC', 'EEC - Environmental Economics'],
        ['EGR', 'EGR - Engineering'],
        ['ELE', 'ELE - Electrical Engineering'],
        ['ELS', 'ELS - English Language Studies'],
        ['ENG', 'ENG - English'],
        ['ENT', 'ENT - Entomology'],
        ['EVS', 'EVS - Environmental Sciences'],
        ['FIN', 'FIN - Finance'],
        ['FLM', 'FLM - Film Media'],
        ['FOS', 'FOS - Forensic Science'],
        ['FRN', 'FRN - French'],
        ['GCH', 'GCH - Grand Challenges'],
        ['GEG', 'GEG - Geography'],
        ['GEO', 'GEO - Geosciences'],
        ['GER', 'GER - German'],
        ['GRK', "GRK - Greek"],
        ['GWS', "GWS - Gender and Women's Studies"],
        ['HBW', 'HBW - Hebrew'],
        ['HDF', 'HDF - Human Development and Family Science'],
        ['HIS', 'HIS - History'],
        ['HLT', 'HLT - Health'],
        ['HPR', 'HPR - Honors Program'],
        ['HSA', 'HSA - Health Services Administration'],
        ['HSS', 'HSS - Human Science and Services'],
        ['INE', 'INE - Innovation and Entrepreneurship'],
        ['ISE', 'ISE - Industrial and Systems Engineering'],
        ['ITL', 'ITL - Italian'],
        ['ITR', 'ITR - Internships/Experiential Education'],
        ['JOR', 'JOR - Journalism'],
        ['JPN', 'JPN - Japanese'],
        ['KIN', 'KIN - Kinesiology'],
        ['LAN', 'LAN - Languages'],
        ['LAR', 'LAR - Landscape Architecture'],
        ['LAS', 'LAS - Latin American Studies'],
        ['LAT', 'LAT - Latin'],
        ['LAX', 'LAX - Latin American, Caribbean and Latinx'],
        ['LET', 'LET - Letters'],
        ['LHR', 'LHR - Labor Relations and Human Resources'],
        ['LIB', 'LIB - Library'],
        ['LIN', 'LIN - Linguistics'],
        ['LSC', 'LSC - Library and Information Studies'],
        ['MAC', 'MAC - Master of Science in Accounting'],
        ['MAF', 'MAF - Marine Affairs'],
        ['MBA', "MBA - Master's in Business Administration"],
        ['MCE', 'MCE - Mechanical Engineering'],
        ['MGT', 'MGT - Management'],
        ['MHM', 'MHM - Master of Science in Healthcare Management'],
        ['MKT', 'MKT - Marketing'],
        ['MLS', 'MLS - Medical Laboratory Science'],
        ['MSL', 'MSL - Military Science and Leadership'],
        ['MTH', 'MTH - Mathematics'],
        ['MUS', 'MUS - Music'],
        ['NES', 'NES - New England Studies'],
        ['NEU', 'NEU - Neuroscience'],
        ['NFS', 'NFS - Nutrition and Food Sciences'],
        ['NRS', 'NRS - Natural Resources Science'],
        ['NUE', 'NUE - Nuclear Engineering'],
        ['NUR', 'NUR - Nursing'],
        ['NVP', 'NVP - Nonviolence and Peace Studies'],
        ['OCE', 'OCE - Ocean Engineering'],
        ['OCG', 'OCG - Oceanography'],
        ['OCS', 'OCS - Off Campus Study - Undergraduate'],
        ['OCSG', 'OCSG - Off Campus Study- Graduate'],
        ['PHC', 'PHC - Pharmacy'],
        ['PHL', 'PHL - Philosophy'],
        ['PHP', 'PHP - Pharmacy Practice'],
        ['PHT', 'PHT - Physical Therapy'],
        ['PHY', 'PHY - Physics'],
        ['PLA', 'PLA - Prior Learning Assessment'],
        ['PLS', 'PLS - Plant Sciences'],
        ['POR', 'POR - Portuguese'],
        ['PRS', 'PRS - Public Relations'],
        ['PSA', 'PSA - Prof Supply Chain & Analytics'],
        ['PSC', 'PSC - Political Science'],
        ['PSY', 'PSY - Psychology'],
        ['RDE', 'RDE - Resource Development Education'],
        ['RIC', 'RIC - Joint PHD program with Rhode Island College'],
        ['RLS', 'RLS - Religious Studies'],
        ['RUS', 'RUS - Russian'],
        ['SAF', 'SAF - Sustainable Agriculture and Food Systems'],
        ['SCA', 'SCA - Supply Chain Management'],
        ['SCM', 'SCM - School of Communication and Media'],
        ['SMC', 'SMC - Sports Media and Communication'],
        ['SOC', 'SOC - Sociology'],
        ['SPA', 'SPA - Spanish'],
        ['SPC', 'SPC - School of Professional and Continuing Studies'],
        ['STA', 'STA - Statistics'],
        ['SUS', 'SUS - Sustainability'],
        ['THE', 'THE - Theatre'],
        ['THN', 'THN - Thanatology'],
        ['TMD', 'TMD - Textiles Fashion Merchandising and Design'],
        ['UCS', 'UCS - University College for Academic Success'],
        ['URB', 'URB - Urban Affairs'],
        ['URI', 'URI - University of Rhode Island Freshman Seminar'],
        ['WRT', 'WRT - Writing']
    ]
);